SClub.ShopSystem.Web/Controllers/BackstageController.cs
using Service;
using SClub.ShopSystem.Web.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web;
using System.Linq;
using SClub.ShopSystem.Web.Service;
using Newtonsoft.Json;

namespace SClub.ShopSystem.Web.Controllers
{
    public class BackstageController : Controller
    {
        private MappingService _mappingService = new MappingService();
        private BackstageService _backstageService = new BackstageService();
        
        // GET: Backstage
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Logout()
        {
            Session.Remove("admin");
            return RedirectToAction("Login");
        }

        public ActionResult IfLogin()
        {
            BackstageService service = new BackstageService();
            var UserId = Request.Form["id"];
            var password = Request.Form["password"];
            Users admin = service.Login(UserId,password);
            if (admin != null)
            {
                List<Permissions> perMissions = _backstageService.GetUserPerMissions(admin.UserId).ToList();
                AdminModel adminModel = _mappingService.GetAdminModel(perMissions, admin);
                Session.Add("admin", adminModel);
                return RedirectToAction("PersonInfo","MenuJump");
            }
            TempData["LoginWrong"] = "登录错误";
            return RedirectToAction("Login");
        }
        
        public ActionResult SideBar()
        {
            var admin = (AdminModel)Session["admin"];
            var menu = _backstageService.GetUserMenu(admin.UserId);
            List<MenuListModel> menuList = menu.Select(a => new MenuListModel
            {
                code = a.code,
                menuFatherId = a.menuFatherId,
                menuId = a.menuId,
                menuName = a.menuName,
                url = a.url,
                children = _mappingService.GetMenuChildren(a.children)
            }).ToList();
            return PartialView(menuList);
        }
        //发货
        public ActionResult Order()
        {
            var OrderId = Convert.ToInt32(Request.Form["submit"]);
            var admin = (AdminModel)Session["admin"];
            var ifOrder= _backstageService.SetDeliverOrderStage(OrderId, admin.UserId);
            Result result = new Result();
            result.url = "/MenuJump/Deliver";
            if (ifOrder == true)
            {
                result.result = "发货成功";
            }
            else
            {
                result.result = "发货失败";
            }
            return View("~/Views/Shared/Result.cshtml", result);
        }
        
        //上架保存
        public ActionResult PutawaySave(Goods goods)
        {
            HttpPostedFileBase hpf = Request.Files["goods[Img]"];
            string fileName = hpf.FileName;
            string path = "/Img/" + fileName;
            string mapPath = Server.MapPath(path);
           
            hpf.SaveAs(mapPath);

            var admin = (AdminModel)Session["admin"];
            var ifPutaway = _backstageService.PutawayNewGoods(goods, path, admin.UserId);
            
            Result result = new Result();
            result.url = "/MenuJump/Putaway";
            if (ifPutaway == true)
            {
                result.result = "上架成功"; 
            }
            else
            {
                result.result = "上架失败";
            }
            return View("~/Views/Shared/Result.cshtml", result);
        }
        //上下架商品
        public ActionResult Unshelve()
        {
            var goodsId = Convert.ToInt32(Request.Form["submit"]);
            var admin = (AdminModel)Session["admin"];
            _backstageService.Unshelve(goodsId, admin.UserId);
            return RedirectToAction("GoodsManage", "MenuJump");
        }
        //商品入库
        public ActionResult InventoryAdd()
        {
            var goodsId = Convert.ToInt32(Request.Form["goodsIdAdd"]);
            var addCount = Convert.ToInt32(Request.Form["AddInventory"]);
            var admin = (AdminModel)Session["admin"];
            var addSuccess = _backstageService.ChangeInventory(goodsId,addCount, admin.UserId);
            Result result = new Result();
            result.url = "/MenuJump/Inventory";
            if (addSuccess == true)
            {
                result.result = "入库成功";
            }
            else
            {
                result.result = "入库失败";
            }
            return View("~/Views/Shared/Result.cshtml", result);
        }
        //商品出库
        public ActionResult InventorySub()
        {
            var subCount = Convert.ToInt32(Request.Form["SubInventory"]);
            var goodsId = Convert.ToInt32(Request.Form["goodsIdSub"]);
            var admin = (AdminModel)Session["admin"];
            var subSuccess = _backstageService.ChangeInventory(goodsId,0 - subCount, admin.UserId);
            Result result = new Result();
            result.url = "/MenuJump/Inventory";
            if (subSuccess == true)
            {
                result.result = "出库成功";
            }
            else
            {
                result.result = "出库失败";
            }
            return View("~/Views/Shared/Result.cshtml", result);
            
        }
        //修改商品信息
        public ActionResult ChangeGoodsInfo(Goods goods)
        {
            HttpPostedFileBase hpf = Request.Files["goodsImg"];
            string fileName = hpf.FileName;
            string path = "/Img/" + fileName;
            string mapPath = Server.MapPath(path);
            var changeGoodsInfo = false;
            try
            {
                hpf.SaveAs(mapPath);
                var admin = (AdminModel)Session["admin"];
                changeGoodsInfo = _backstageService.ChangeGoodsInfo(goods, path, admin.UserId);
                Result result = new Result();
                result.url = "/MenuJump/GoodsManage";
                if (changeGoodsInfo == true)
                {
                    result.result = "修改成功";
                }
                else
                {
                    result.result = "修改失败";
                }
                return View("~/Views/Shared/Result.cshtml", result);
               
            }
            catch(Exception e)
            {
                var admin = (AdminModel)Session["admin"];
                changeGoodsInfo = _backstageService.ChangeGoodsInfo(goods, goods.Img, admin.UserId);
                Result result = new Result();
                result.url = "/MenuJump/GoodsManage";
                if (changeGoodsInfo == true)
                {
                    result.result = "修改成功";
                }
                else
                {
                    result.result = "修改失败";
                }
                return View("~/Views/Shared/Result.cshtml", result);
            }
           
           

        }
        public ActionResult ResetPassword(string UserId)
        {
            _backstageService.ResetPasswordById(Convert.ToInt32(UserId));
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        //修改头像
        public ActionResult ChangeAdminImg()
        {
            HttpPostedFileBase hpf = Request.Files["goods[Img]"];
            string fileName = hpf.FileName;
            string path = "/Img/" + fileName;
            string mapPath = Server.MapPath(path);

            hpf.SaveAs(mapPath);
            var userId = Convert.ToInt32(Request.Form["adminId"]);
            _backstageService.ChangeAdminImg(userId, path);
            ((AdminModel)Session["admin"]).UserImg = path;
            return RedirectToAction("PersonInfo", "MenuJump");
        }
        //修改密码
        public ActionResult ChangePassword()
        {
            var userId = Convert.ToInt32(Request.Form["adminId"]);
            var password = Request.Form["password"];
            _backstageService.ChangePassword(userId, password);
            return RedirectToAction("PersonInfo", "MenuJump");
        }

        //获取所有权限
        public ActionResult GetAllRoles(string userId)
        {
            
            var roleTree = _mappingService.GetPermissonAndRoleTree(_backstageService.GetAllPerMissions(), _backstageService.GetUserPerMission(Convert.ToInt32(userId)));
            var json = JsonConvert.SerializeObject(roleTree);
            return Json(json,JsonRequestBehavior.AllowGet);
        }
        public ActionResult PermissionManage(string userId,string[] permissions)
        {
            var result = _backstageService.PermissManage(Convert.ToInt32(userId), permissions);
            return Json(result,JsonRequestBehavior.AllowGet);
        }
        public ActionResult ChangeRecommendImg(string id)
        {
            HttpPostedFileBase hpf = Request.Files["file"];
            string fileName = hpf.FileName;
            string path = "/Img/" + fileName;
            string mapPath = Server.MapPath(path);
            hpf.SaveAs(mapPath);
            var result = _backstageService.ChangeRemcommendImg(Convert.ToInt32(id), path);
            if (!result)
            {
                return null;
            }
            return Json(JsonConvert.SerializeObject(path), JsonRequestBehavior.AllowGet);
        }
    }
}

SClub.ShopSystem.Web/Views/Backstage/HomePage.cshtml
@{
    ViewBag.Title = "HomePage";
    Layout = ("~/Views/Backstage/_BackstageLayout.cshtml");
}

@*@if ((string)TempData["MenuJump"] == "个人信息" || (string)TempData["MenuJump"] == null)
{
    @Html.Action("PersonInfo", "MenuJump")
}

@if ((string)TempData["MenuJump"] == "信息统计")
{
    @Html.Action("CountInfo", "MenuJump")
}

@if ((string)TempData["MenuJump"] == "待发货")
{
    @Html.Action("Deliver", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "待收货")
{
    @Html.Action("ReceiptGoods", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "交易记录")
{
    @Html.Action("GoodsRecord", "MenuJump")
}

@if ((string)TempData["MenuJump"] == "商品管理")
{
    @Html.Action("GoodsManage", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "上架商品")
{
    @Html.Action("Putaway", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "商品推荐")
{
    @Html.Action("GoodsRecommend", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "库存管理")
{
    @Html.Action("Inventory", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "员工管理")
{
    @Html.Action("UserManage", "MenuJump")
}
@if ((string)TempData["MenuJump"] == "操作记录")
{
    @Html.Action("Recording", "MenuJump")
}*@

SClub.ShopSystem.Web/Views/Backstage/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Css/login.css" rel="stylesheet" />
    <title>后台登录</title>
</head>
<body>
    @if ((string)TempData["IfLogin"] == "未登录")
    {
        <script language="JavaScript">alert("请先登录再进入系统！")</script>
    }
   
    <div id="login">

        <h2><span class="fontawesome-lock"></span>后台登录</h2>

        <form action="IfLogin" method="post">

            <fieldset>
                @if ((string)TempData["LoginWrong"] == "登录错误")
                {
                    <p><label id="wrong" style="color:red">用户名或密码错误</label></p>
                }
                <p><label for="id">账号</label></p>
                <p><input id="in" name="id"></p> 

                <p><label >密码</label></p>
                <p><input type="password" id="in" name="password"></p>

                <p><input type="submit" id="signin" value="Sign in" onclick="CheckIfLogin(id.value,password.value)"></p>

                
            </fieldset>

        </form>

    </div> 
    @*<script src="~/Js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">
        function CheckIfLogin(id,password)
        {
            $.ajax({
                url: "/Backstage/IfLogin",
                type: "GET",
                data: {
                    "id": id,
                    "password":password
                },
                dataType: "Json",
                error: function (xhr) {
                    alert('Error: ' + xhr.statusText);
                },
                success: function () {

                    var wrong = ""
                    wrong += "<label style=\"color:red\">用户名或密码错误</label>"
                    document.getElementById("wrong").innerHTML = wrong;
                }

            })
            }
    </script>*@
</body>	

</html>

SClub.ShopSystem.Web/Views/Backstage/SideBar.cshtml
@model List<SClub.ShopSystem.Web.Models.MenuListModel>
@{ 
    var a = Model;
}
@foreach (var menu in Model)
{
    <li class="treeview">
        <a href="@menu.url">
            <i class="fa fa-circle-o"></i> <span>@menu.menuName</span>
            <span class="pull-right-container">
                @if (menu.children.Count != 0)
                {
                    <i class="fa fa-angle-left pull-right"></i>
                }

            </span>
        </a>
        @if (menu.children.Count != 0)
        {
            <ul class="treeview-menu">
                @Html.Partial("SideBar", menu.children)
            </ul>
        }

    </li>
}

SClub.ShopSystem.Web/Views/Backstage/_BackstageLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
   
    @Styles.Render("~/Css/Backstage/Layout/bootstrap.min.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css")
    @Styles.Render("~/Css/Backstage/Layout/AdminLTE.min.css")
    @Styles.Render("~/Css/Backstage/Layout/_all-skins.min.css")
    @Styles.Render("~/Js/layui/css/layui.css")
    @Scripts.Render("~/Js/Backstage/Layout/jquery-2.2.3.min.js")
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">


</head>
<body class="hold-transition skin-blue sidebar-mini" style="height:1000px;padding:0">
    <div class="wrapper">

        
        @Html.Partial("~/Views/Backstage/_Header.cshtml")
        @Html.Partial("~/Views/Backstage/_SideMenu.cshtml")
        <div class="content-wrapper"style="height:1000px;padding:0;margin-top:0px;">
            @RenderBody()
        </div>
            
        </div>


    
    <!-- jQuery UI 1.11.4 -->
    @Scripts.Render("~/Js/Backstage/Layout/bootstrap.min.js")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js")
    @Scripts.Render("~/Js/MenuJump/public.js")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js")

    @Scripts.Render("~/Js/Backstage/Layout/app.min.js")
    @Scripts.Render("~/Js/Backstage/Layout/demo.js")
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <!-- Bootstrap 3.3.6 -->


</body>
</html>

SClub.ShopSystem.Web/Views/Backstage/_Header.cshtml
@using SClub.ShopSystem.Web.Models;
@{
    AdminModel user = (AdminModel)Session["admin"];
}
<header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>E</b>S</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>E</b>Sports</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">你有四条未读消息</li>
                        
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                <!-- Notifications: style can be found in dropdown.less -->
                
                <!-- Tasks: style can be found in dropdown.less -->
                
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="@user.UserImg" class="user-image" alt="User Image">
                        <span class="hidden-xs">@user.Name</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="@user.UserImg" class="img-circle" alt="User Image">
                            <p>
                                @user.Name
                                <small>入职时间:@user.CreationTime</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                            <!-- /.row -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">账号：@user.Account</a>
                            </div>
                            
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
                <li>
                    <a href="/Backstage/Logout" ><i class="fa fa-sign-out"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

SClub.ShopSystem.Web/Views/Backstage/_SideMenu.cshtml
@using SClub.ShopSystem.Web.Models;
@{
    AdminModel user = (AdminModel)Session["admin"];
}
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="@user.UserImg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@user.Name</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li class="header">菜单</li>
            @Html.Action("SideBar", "Backstage")
        </ul>
    </section>
</aside>